# Generated by Django 2.2.6 on 2022-10-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aulas',
            name='nome_aula',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
