# Generated by Django 2.2.6 on 2022-10-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_aulas_nome_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='aulas',
            name='categoria',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
