# Generated by Django 2.2.6 on 2022-10-17 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
        ('login', '0003_aulas_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='aulas',
            name='pessoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoas.Pessoa'),
        ),
    ]
