# Generated by Django 2.2.6 on 2022-10-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20221017_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='aulas',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
